# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ""

setup(
    long_description=readme,
    name="flask-slapos",
    version="1.0.1",
    description="Sample Flask project for SlapOS",
    python_requires="==3.*,>=3.7.0",
    author="Stefane Fermigier and others",
    install_requires=["flask==2.*,>=2.0.0", "gunicorn==20.*,>=20.0.0"],
)
